# Mapping from Chinese exercise name -> PNG icon filename
EXERCISE_ICON_MAP = {
    "卧推": "ex_bench.png",
    "深蹲": "ex_squat.png",
    "硬拉": "ex_deadlift.png",
    "引体向上": "ex_pullup.png",
    "杠铃划船": "ex_row.png",
    "推举": "ex_press.png",
    "哑铃弯举": "ex_curl.png",
    "臂屈伸": "ex_dip.png",
    "俯卧撑": "ex_pushup.png",
    "卷腹": "ex_crunch.png",
    "腿举": "ex_legpress.png",
    "飞鸟": "ex_fly.png",
    "跑步": "ex_run.png",
    "游泳": "ex_swim.png",
    "骑行": "ex_bike.png",
    "椭圆机": "ex_elliptical.png",
    "跳绳": "ex_rope.png",
    "爬楼": "ex_stairs.png",
    "快走": "ex_walk.png",
    "HIIT": "ex_hiit.png",
    "划船机": "ex_rowing.png",
    "登山": "ex_hike.png",
    "滑雪": "ex_ski.png",
    "瑜伽": "ex_yoga.png",
}
